<?php
/**
 * 2011-2018 PH2M
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@ph2m.com so we can send you a copy immediately.
 *
 * @author PH2M - contact@ph2m.com
 * @copyright 2011-2018 PH2M
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

/** @var $block \PH2M\Captcha\Block\Captcha */
?>
<?php if ($block->isEnabled()): ?>
    <button type="submit"
            title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
            class="action submit primary g-recaptcha"
            data-sitekey="<?php echo $block->getSiteKey() ?>"
            data-callback="onSubmit">
        <span><?= $block->escapeHtml(__('Submit')) ?></span>
    </button>

    <script>
        function onSubmit(token) {
            document.getElementById("contact-form").submit();
        }
    </script>
<?php else: ?>
    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
        <span><?= $block->escapeHtml(__('Submit')) ?></span>
    </button>
<?php endif ?>